---
# tasks file for mlynn.mongodb-opsmgr

- name: Copy repo
  copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo owner=root group=root mode="u=rw,g=r,o=r"

- name: Create mongod user
  user: name=mongod comment="MongoD"

- name: Create Data Directories
  file: path=/data state=directory mode=0755 owner=mongod group=mongod

- name: Update all packages
  yum: name=* state=latest

- name: Install Latest MongoDB
  yum: name=mongodb-org state=latest

- name: Install mongodb shell
  yum: name=mongodb-org-shell state=latest

- name: Install gpg
  yum: name=gpg state=latest

- name: disable hugepage support
  shell: /bin/echo never | /usr/bin/sudo /usr/bin/tee /sys/kernel/mm/transparent_hugepage/enabled

- name: disable hugepage defrag
  shell: /bin/echo never | /usr/bin/sudo /usr/bin/tee /sys/kernel/mm/transparent_hugepage/defrag

- service:
  name: mongod
  state: started
